FROM libxml2-base

RUN apt-get update && apt-get install -y \
    afl \
    gcc \
    clang20.1 \
    && apt-get clean

WORKDIR /src/libxml2

ENV CC=afl-clang-fast
ENV CXX=afl-clang-fast++
ENV AFL_SKIP_CPUFREQ=1

RUN make distclean || true \
 && ./autogen.sh \
 && ./configure --disable-shared \
 && make -j$(nproc)

RUN mkdir -p in out /report \
 && echo "<root><root/>" > in/seed.xml

CMD timeout 15m \
    afl-fuzz \
      -i in \
      -o out \
      -t 1000 \
      -m none \
      -- ./xmllint @@
