FROM silkeh/clang:18-bookworm

RUN apt-get update && apt-get install -y \
    git \
    make \
    autoconf \
    libtool \
    pkg-config \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
    
ARG LIBXML2_VERSION=v2.12.10
ARG SISYPHUS_REPO=git://git.altlinux.org/gears/l/libxml2.git

WORKDIR /src

RUN git clone --depth 1 --branch ${LIBXML2_VERSION} ${SISYPHUS_REPO} libxml2

WORKDIR /src/libxml2
RUN ./autogen.sh
RUN ./configure 

RUN mkdir -p /report

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
	
