FROM alt/sisyphus

RUN apt-get update && apt-get install -y \
    git \
    make \
    autoconf \
    libtool \
    pkg-config \
    python3-dev \
    clang20.1-analyzer \
    llvm \
    llvm20.1 \
    && apt-get clean

    
ARG LIBXML2_VERSION=v2.12.10
ARG SISYPHUS_REPO=git://git.altlinux.org/gears/l/libxml2.git

WORKDIR /src

RUN git clone --depth 1 --branch ${LIBXML2_VERSION} ${SISYPHUS_REPO} libxml2

WORKDIR /src/libxml2
RUN ./autogen.sh && ./configure 

RUN mkdir -p /report

CMD make clean && scan-build -o /report --use-cc=clang make -j$(nproc)
