FROM libxml2-base

RUN apt-get update && apt-get install -y \
    clang20.1-analyzer \
    llvm \
    llvm20.1 \
    && apt-get clean

RUN mkdir -p /report

CMD make clean && scan-build -o /report --use-cc=clang make -j$(nproc)
